
import { supabase } from "@/integrations/supabase/client";
import { AuditResult } from "@/services/pdfAnalyzer";
import { ClientReport } from "@/types/client";
import { toast } from "sonner";
import { v4 as uuidv4 } from "uuid";

/**
 * Generate a report using the Gemini API
 * @param auditData The audit data to be processed
 * @param templateType The type of report template to use (seo, local, etc.)
 * @returns The generated report content
 */
export const generateGeminiReport = async (
  auditData: AuditResult, 
  templateType: 'seo' | 'local' | 'technical' | 'performance' = 'seo'
): Promise<string | null> => {
  try {
    console.log("Generating report with Gemini API");
    console.log("Template type:", templateType);
    console.log("Audit data:", JSON.stringify(auditData, null, 2));
    
    // Validate essential data
    if (!auditData || !auditData.companyName) {
      throw new Error("Datos de auditoría incompletos. Se requiere al menos el nombre de la empresa.");
    }
    
    // Call the Supabase Edge Function for Gemini
    const { data, error } = await supabase.functions.invoke('gemini-report', {
      body: {
        auditData,
        templateType
      }
    });
    
    if (error) {
      console.error("Error calling Gemini API:", error);
      throw new Error(`Error llamando a Gemini API: ${error.message}`);
    }
    
    if (!data) {
      console.error("No data received from Gemini API");
      throw new Error("No se recibieron datos de la API de Gemini");
    }
    
    if (!data.content) {
      console.error("No content in Gemini API response:", data);
      throw new Error("No se recibió contenido de la API de Gemini");
    }
    
    console.log("Report generated successfully");
    return data.content;
  } catch (error) {
    console.error("Error in generateGeminiReport:", error);
    toast.error("Error generando el informe con Gemini: " + 
      (error instanceof Error ? error.message : "Error desconocido"));
    return null;
  }
};

/**
 * Save a report generated by Gemini to the database
 * @param clientId The client ID
 * @param clientName The client name
 * @param reportContent The generated report content
 * @param auditData The audit data used to generate the report
 * @param documentIds Optional array of document IDs used in the report
 * @returns The saved report object
 */
export const saveGeminiReport = async (
  clientId: string,
  clientName: string,
  reportContent: string,
  auditData: AuditResult,
  documentIds: string[] = []
): Promise<ClientReport | null> => {
  try {
    console.log("Saving Gemini report to database for client:", clientId);
    
    // Create a serializable version of auditData for storage
    let serializableAuditData;
    try {
      serializableAuditData = JSON.parse(JSON.stringify(auditData));
    } catch (err) {
      console.error("Error serializing audit data:", err);
      serializableAuditData = { error: "Data could not be serialized" };
    }
    
    const reportData = {
      client_id: clientId,
      title: `Informe SEO - ${clientName} - ${new Date().toLocaleDateString('es-ES')}`,
      date: new Date().toISOString(),
      type: "seo",
      content: reportContent,
      analytics_data: {
        auditResult: serializableAuditData,
        generatedAt: new Date().toISOString(),
        generatedBy: "gemini"
      },
      document_ids: documentIds,
      status: 'draft'
    };
    
    console.log("Inserting report into database");
    
    // Save to database
    const { data, error } = await supabase
      .from('client_reports')
      .insert(reportData)
      .select()
      .single();
    
    if (error) {
      console.error("Error saving report to database:", error);
      throw new Error(`Error guardando el informe: ${error.message}`);
    }
    
    console.log("Report saved successfully with ID:", data.id);
    
    // Map database response to ClientReport type
    return {
      id: data.id,
      clientId: data.client_id,
      title: data.title,
      date: data.date,
      type: data.type,
      content: data.content,
      analyticsData: data.analytics_data,
      documentIds: data.document_ids || [],
      url: data.url,
      notes: data.notes,
      shareToken: data.share_token,
      sharedAt: data.shared_at,
      includeInProposal: data.include_in_proposal || false,
      status: data.status || 'draft'
    };
  } catch (error) {
    console.error("Error in saveGeminiReport:", error);
    toast.error("Error guardando el informe: " + 
      (error instanceof Error ? error.message : "Error desconocido"));
    return null;
  }
};

/**
 * Generate a report using Gemini and save it to the database
 * @param clientId The client ID
 * @param clientName The client name
 * @param auditData The audit data to use for generation
 * @param documentIds Optional array of document IDs used in the report
 * @returns The saved report object
 */
export const generateAndSaveReport = async (
  clientId: string,
  clientName: string,
  auditData: AuditResult,
  documentIds: string[] = []
): Promise<ClientReport | null> => {
  try {
    console.log("Starting generateAndSaveReport for client:", clientId, clientName);
    toast.loading("Generando informe con IA...");
    
    // Ensure auditData has the client name
    const enhancedAuditData = {
      ...auditData,
      companyName: clientName
    };
    
    // Determine the report type based on the audit data
    let reportType: 'seo' | 'local' | 'technical' | 'performance' = 'seo';
    if (enhancedAuditData.localData && enhancedAuditData.localData.businessName) {
      reportType = 'local';
    } else if (enhancedAuditData.technicalResults && Object.keys(enhancedAuditData.technicalResults).length > 0) {
      reportType = 'technical';
    } else if (enhancedAuditData.performanceResults && Object.keys(enhancedAuditData.performanceResults).length > 0) {
      reportType = 'performance';
    }
    
    console.log(`Using report type: ${reportType}`);
    
    // Generate the report content
    const reportContent = await generateGeminiReport(enhancedAuditData, reportType);
    
    if (!reportContent) {
      toast.dismiss();
      toast.error("No se pudo generar el contenido del informe");
      return null;
    }
    
    console.log("Report content generated, saving to database");
    
    // Save the report
    const savedReport = await saveGeminiReport(
      clientId,
      clientName,
      reportContent,
      enhancedAuditData,
      documentIds
    );
    
    toast.dismiss();
    
    if (savedReport) {
      toast.success("Informe generado y guardado correctamente");
      return savedReport;
    } else {
      toast.error("Error guardando el informe");
      return null;
    }
  } catch (error) {
    toast.dismiss();
    console.error("Error in generateAndSaveReport:", error);
    toast.error("Error en el proceso de generación del informe: " + 
      (error instanceof Error ? error.message : "Error desconocido"));
    return null;
  }
};
