
project_id = "gwscyovvgivbtqtmbdth"
name = "openai-report"
models = [
  { name = "config.ts", content_type = "application/typescript; charset=utf-8", path = "../commons/config.ts" }
]
[[env.options]]
name = "OPENAI_API_KEY"
description = "OpenAI API key"
[[env.options]]
name = "OPENAI_MODEL"
description = "OpenAI model to use (gpt-4o-mini, gpt-4o)"
default = "gpt-4o-mini"
