
project_id = "gwscyovvgivbtqtmbdth"
[parameters]
allowed_environments = ["dev", "staging", "prod"]
# Gemini API key not needed as service is now using OpenAI
# GEMINI_API_KEY = "REMOVED - Service deprecated"

